steps:
  - name: google/cloud-sdk:alpine
    id: Update git submodules
    entrypoint: git
    args: 
      [
        'submodule', 
        'update', 
        '--init', 
        '--recursive'
      ]
  - name: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/hpc-toolkit/hpc-toolkit"
    entrypoint: /ghpc-tmp/ghpc
    args:
      [
        'create',
        '/workspace/hpc-toolkit/blueprints/hpc-cluster-small.yaml',
        '--vars',
        "billing_account=${_BILLING_ACCOUNT},org_id=${_ORGANIZATION_ID},folder_id=${_FOLDER_ID},project_id=${_GHPC_PROJECT_ID},deployment_name=${_REQUEST_ID},region=${_REGION},zone=${_REGION}-a",
        '--backend-config',
        "bucket=${_STORAGE_BUCKET}"
      ]
  - name: "gcr.io/${PROJECT_ID}/terraform"
    args:
      [
        "-chdir=${_REQUEST_ID}/primary",
        "init"
      ]
  - name: "gcr.io/${PROJECT_ID}/terraform"
    args: ["-chdir=${_REQUEST_ID}/primary", "apply", "-auto-approve"]
substitutions:
  _GHPC_PROJECT_ID: hpc-cluster-small-${_REQUEST_ID:0:12}
timeout: 2700s
